//------------------------------------------------------------------------
// Copyright(c) 2025 My Plug-in Company.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"VolumeKnob.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"VolumeKnob VST3 (64Bit)"
#else
#define stringFileDescription	"VolumeKnob VST3"
#endif
#define stringCompanyName		"My Plug-in Company\0"
#define stringLegalCopyright	"Copyright(c) 2025 My Plug-in Company."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
